name: C/C++ CI

on:
  pull_request:
  workflow_dispatch:
  push:
    branches-ignore:
      - '_**'
      - '**wip**'

jobs:
  build:
    if: ${{ ! startsWith(github.event.head_commit.message, 'WIP') }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install criterion
      run: sudo apt install --no-install-recommends libcriterion-dev
    - name: Make binaries
      run: make lisp test-lisp
    - name: Test
      run: make test
    - name: Make binaries for Clang
      run: make clean lisp test-lisp CC=clang
    - name: Test for Clang
      run: make test CC=clang
    - name: Test -O3
      run: make clean all XCFLAGS=-O3
    - name: Test Clang -O3
      run: make clean all CC=clang XCFLAGS=-O3
