name: C/C++ CI

on:
  pull_request:
  workflow_dispatch:
  push:
    branches-ignore:
      - '_**'
      - '**wip**'

jobs:
  build:
    if: ${{ ! startsWith(github.event.head_commit.message, 'WIP') }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - if: runner.os == 'Linux'
      run: |
        sudo apt update
        sudo apt install --no-install-recommends libcriterion-dev
    - if: runner.os == 'macOS'
      run: |
        brew update
        brew install criterion
        echo CPATH="/opt/homebrew/include:$CPATH" >> "$GITHUB_ENV"
        echo LIBRARY_PATH="/opt/homebrew/lib:$LIBRARY_PATH" >> "$GITHUB_ENV"
    - name: Make binaries
      run: make -j2 lisp basic-test
    - name: Test
      run: make test
    - name: Make binaries for Clang
      run: make clean && make -j2 lisp basic-test CC=clang
    - name: Test for Clang
      run: make test CC=clang
    - name: Test -O3
      run: make clean && make -j2 test XCFLAGS=-O3
    - name: Test Clang -O3
      run: make clean && make -j2 test CC=clang XCFLAGS=-O3
