name: C/C++ CI

on:
  pull_request:
  workflow_dispatch:
  push:
    branches-ignore:
      - '.**'
      - '**wip**'

jobs:
  build:
    if: ${{ ! startsWith(github.event.head_commit.message, 'WIP') }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install criterion
      run: sudo apt install --no-install-recommends libcriterion-dev
    - name: make
      run: make
    - name: test
      run: make test
